In [ ]:


import numpy as np
import pandas as pd
from numpy import random
import os
os.getcwd()     #get current working directory
os.chdir("/content/drive/MyDrive")
os.getcwd
df=pd.read_excel('CDAC_DataBook (1).xlsx',sheet_name='ERPData')
df.head()       #by default 5 rows ahe shown
import scipy
from scipy import stats
from scipy.stats import norm,t
from collections import Counter
from scipy.stats import binom
from scipy.stats import poisson
from scipy.stats import expon



import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import pylab
from pylab import legend
from pylab import plot,show,title,xlabel,ylabel


import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest

from statsmodels.stats import rates


from statsmodels.stats.rates import test_poisson_2indep

from scipy.stats import chi2

from scipy.stats import f

import sklearn

from sklearn.linear_model import LinearRegression

from sklearn.model_selection import cross_val_score

from sklearn.metrics import mean_squared_error

from sklearn.model_selection import train_test_split

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from statsmodels.stats.outliers_influence import variance_inflation_factor

# ONE HOT ENCODING :

USED FOR NOMINAL SCALE VARIABLES (NO LOGICAL ORDER)

NOT USEFUL WHEN NUMBER OF CATEGORIES ARE TOO LARGE

REGRESSION ,ANN,KNN,SVM

# ORDINAL ENCODING

VARIABLES WITH INHERENT RANKING OR RATING

PRESERVE LOGICAL ORDER

In [ ]:
df = pd.DataFrame({
    'Education':[
        'Graduate',
        'PG',
        'High School',
        'Graduate',
        'PG'
    ]
})

education_map = {
    'High School':1,
    'Graduate':2,
    'PG':3
}

df['Education_Encoded'] = (
    df['Education']
    .map(education_map)
)

print(df)

     Education  Education_Encoded
0     Graduate                  2
1           PG                  3
2  High School                  1
3     Graduate                  2
4           PG                  3

# **Frequency Encoding**

In [ ]:
# Frequency encoding
df = pd.DataFrame({
    'City':[
        'Mumbai',
        'Mumbai',
        'Mumbai',
        'Delhi',
        'Delhi',
        'Pune'
    ]
})

freq = df.City.value_counts()

df['City_Frequency'] = (df.City.map(freq))

In [ ]:
freq

City
Mumbai    3
Delhi     2
Pune      1
Name: count, dtype: int64

In [ ]:
df

     City  City_Frequency
0  Mumbai               3
1  Mumbai               3
2  Mumbai               3
3   Delhi               2
4   Delhi               2
5    Pune               1

# **binary encoding**

it is used when number of category is very large

In [ ]:
pip install category_encoders

Requirement already satisfied: category_encoders in /usr/local/lib/python3.12/dist-packages (2.9.0)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (26.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)

In [ ]:
from category_encoders import BinaryEncoder

In [ ]:
df = pd.DataFrame({
    'City': [
        'Mumbai',
        'Pune',
        'Delhi',
        'Chennai',
        'Kolkata'
    ]
})

In [ ]:
encoder = BinaryEncoder(cols=['City'])

In [ ]:
df_encoded = encoder.fit_transform(df)
print(df_encoded)

   City_0  City_1  City_2
0       0       0       1
1       0       1       0
2       0       1       1
3       1       0       0
4       1       0       1

In [ ]:
df_encoded = encoder.transform(df)

In [ ]:
result = pd.concat([df, df_encoded], axis=1)
print(result)

      City  City_0  City_1  City_2
0   Mumbai       0       0       1
1     Pune       0       1       0
2    Delhi       0       1       1
3  Chennai       1       0       0
4  Kolkata       1       0       1

# **Confusion Matrix**

In [ ]:
df = pd.read_excel('CDAC_DataBook (1).xlsx', sheet_name = 'diabetes')

df =df[['Glucose','BloodPressure','Age','DietType','Outcome']]

x = df.drop('Outcome', axis=1)
y = df.Outcome        #response
diet_dummy = pd.get_dummies(x.DietType, drop_first=True, prefix='Diet').astype(int)
x = x.drop('DietType', axis=1)

In [ ]:
x=pd.concat([x,diet_dummy],axis=1)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

In [ ]:
x_test = sm.add_constant(x_test, prepend=False)

In [ ]:
x_train = sm.add_constant(x_train, prepend=False)

In [ ]:
mod3 = sm.Logit(y_train, x_train).fit()

Optimization terminated successfully.
         Current function value: 0.333614
         Iterations 7

In [ ]:
y_pred = mod3.predict(x_test)

In [ ]:
y_pred=[]

In [ ]:
for ctr in y_pred_prob:
  if ctr >=0.5:
    y_pred.append(1)
  else:
    y_pred.append(0)

NameError: name 'y_pred_prob' is not defined

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
print(confusion_matrix(y_test,y_pred))

In [ ]:
print(classification_report(y_test,y_pred))

In [ ]:
164/(264+47)

0.5273311897106109

In [ ]:
362/(362+51)

0.8765133171912833

In [ ]:
362/(362+51)

0.8765133171912833