In [3]:
import numpy as np
import pandas as pd
from numpy import random
import os
os.getcwd()     #get current working directory
os.chdir("/content/drive/MyDrive")
os.getcwd
df=pd.read_excel('CDAC_DataBook (1).xlsx',sheet_name='ERPData')
df.head()       #by default 5 rows ahe shown
import scipy
from scipy import stats
from scipy.stats import norm,t
from collections import Counter
from scipy.stats import binom
from scipy.stats import poisson
from scipy.stats import expon



import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import pylab
from pylab import legend
from pylab import plot,show,title,xlabel,ylabel


import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp


import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest



from statsmodels.stats import rates


from statsmodels.stats.rates import test_poisson_2indep

from scipy.stats import chi2

from scipy.stats import f

import sklearn

from sklearn.linear_model import LinearRegression

from sklearn.model_selection import cross_val_score

from sklearn.metrics import mean_squared_error

from sklearn.model_selection import train_test_split

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.metrics import log_loss

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# **AUC-ROC CURVE**

**AUC** - area under curve

**ROC** - receiver operating charectertistics

In [4]:
from sklearn.metrics import roc_auc_score

In [5]:
y_true=[1,0,0,1,1,0]

In [6]:
y_pred=[0.93,0.83,0.31,0.73,0.25,0.37]

In [7]:
roc_auc_score(y_true,y_pred)

np.float64(0.5555555555555556)

In [8]:
5/9

0.5555555555555556

# **Normal Logistic Regression**

In [9]:
from statsmodels.discrete.discrete_model import MNLogit

In [10]:
df = pd.read_excel('CDAC_DataBook (1).xlsx', sheet_name='nominal')
df = df.drop('write', axis=1)

x = df.drop('prog', axis=1)
y = df.prog

ses_dummy = pd.get_dummies(x.ses, drop_first=True, prefix='SES').astype(int)
x.drop('ses', axis=1, inplace=True)
x = pd.concat([x,ses_dummy], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

x_train = sm.add_constant(x_train, prepend=False)
mod1 = sm.MNLogit(y_train, x_train).fit()
print(mod1.summary())

Optimization terminated successfully.
         Current function value: 0.653667
         Iterations 8
                          MNLogit Regression Results
==============================================================================
Dep. Variable:                   prog   No. Observations:                  160
Model:                        MNLogit   Df Residuals:                      152
Method:                           MLE   Df Model:                            6
Date:                Tue, 09 Jun 2026   Pseudo R-squ.:                  0.3687
Time:                        11:10:28   Log-Likelihood:                -104.59
converged:                       True   LL-Null:                       -165.68
Covariance Type:            nonrobust   LLR p-value:                 5.678e-24
==============================================================================
    prog=2       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
math           0.0112      0.036      0.312      0.755      -0.059       0.082
SES_2          3.2174      0.685      4.695      0.000       1.874       4.561
SES_3          2.4719      1.121      2.204      0.028       0.274       4.670
const         -1.0727      1.747     -0.614      0.539      -4.496       2.351
------------------------------------------------------------------------------
    prog=3       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
math           0.1181      0.042      2.797      0.005       0.035       0.201
SES_2          5.4410      1.237      4.399      0.000       3.017       7.865
SES_3          6.7918      1.486      4.570      0.000       3.879       9.705
const         -9.3380      2.542     -3.674      0.000     -14.319      -4.357
==============================================================================

In [13]:
#the ses 1 progrma pick ses2 progrma

In [14]:
x_train.head()

     math  SES_2  SES_3  const
152    51      1      0    1.0
67     49      1      0    1.0
133    57      0      1    1.0
59     54      0      1    1.0
63     40      1      0    1.0

In [15]:
mydata=pd.DataFrame([[60,0,0,1],[60,1,0,1]], columns=x_train.columns)

In [16]:
mydata

   math  SES_2  SES_3  const
0    60      0      0      1
1    60      1      0      1

In [17]:
mod1.predict(mydata)

         0         1         2
0  0.56349  0.377273  0.059237
1  0.02383  0.398299  0.577871

# **Ordinal Logistic Regression**

The ordinal logistic regression is used when response in multiple categories with logical order.

The response would be like rating and ranking

In [18]:
from statsmodels.miscmodels.ordinal_model import OrderedModel

df = pd.read_excel('CDAC_DataBook (1).xlsx', sheet_name='ordinal')

reg_dummy = pd.get_dummies(df.Region, drop_first=True, prefix='Region').astype(int)
df.drop('Region', axis=1, inplace=True)
df = pd.concat([df,reg_dummy], axis=1)
df.Survival = pd.Categorical(df.Survival, categories=[1,2,3],ordered=True)  # survival col is categorical data ,, order = true is required

x_train, x_test, y_train, y_test = train_test_split(df.drop('Survival',axis=1),df.Survival,test_size=0.2, random_state=20)

mod1=OrderedModel(y_train,x_train,distr='logit').fit(method='bfgs')
print(mod1.summary())

Optimization terminated successfully.
         Current function value: 0.847944
         Iterations: 19
         Function evaluations: 22
         Gradient evaluations: 22
                             OrderedModel Results
==============================================================================
Dep. Variable:               Survival   Log-Likelihood:                -49.181
Model:                   OrderedModel   AIC:                             106.4
Method:            Maximum Likelihood   BIC:                             114.6
Date:                Tue, 09 Jun 2026
Time:                        11:10:42
No. Observations:                  58
Df Residuals:                      54
Df Model:                           2
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ToxicLevel    -0.1255      0.039     -3.196      0.001      -0.203      -0.049
Region_2      -0.6543      0.547     -1.197      0.231      -1.726       0.417
1/2           -7.4417      1.924     -3.867      0.000     -11.213      -3.670
2/3            1.1827      0.158      7.467      0.000       0.872       1.493
==============================================================================

In [19]:
df.head()

  Survival  ToxicLevel  Region_2
0        1        62.0         0
1        1        46.0         1
2        2        48.5         0
3        3        32.0         1
4        2        63.5         0

In [ ]:
# 3 is best and 1 is the worst
# 3 is better than 2 and 2 is better than

In [ ]:
#survival rating is depends of toxic level
# as the toxic level increases your survial rating changes like 3-2, 2-1
# toxic -- contineous data
# region --- categorical data

In [20]:
mydata=pd.DataFrame([[40,1],[50,1],[60,1],[80,1]],columns=x_train.columns)

In [21]:
mod1.predict(mydata)

          0         1         2
0  0.146074  0.671128  0.182797
1  0.375119  0.564959  0.059922
2  0.678108  0.304052  0.017840
3  0.962885  0.035642  0.001473

In [ ]:
# when the chances of  toxic level increasing the chances of survival is decreasing .

two model  :

--possion

--counts

In [23]:
import statsmodels.formula.api as smf
from statsmodels.discrete.discrete_model import Poisson as psn
df = pd.read_excel('CDAC_DataBook (1).xlsx', sheet_name='poisson')
prog_dummy = pd.get_dummies(df.prog, drop_first=True,prefix='prog').astype(int)
df = df.drop('prog', axis=1)
df = pd.concat([df,prog_dummy], axis=1)
x_train, x_test, y_train, y_test = train_test_split(df.drop('num_awards', axis=1), df['num_awards'], test_size=0.2,random_state=20)
x_train1 = sm.add_constant(x_train, prepend=False)

df_train = pd.concat([x_train1,y_train], axis=1)

mod2 = psn.from_formula("num_awards ~ math+prog_2+prog_3", data=df_train).fit()

Optimization terminated successfully.
         Current function value: 0.871654
         Iterations 6

In [25]:
print(mod2.summary())

                          Poisson Regression Results
==============================================================================
Dep. Variable:             num_awards   No. Observations:                  160
Model:                        Poisson   Df Residuals:                      156
Method:                           MLE   Df Model:                            3
Date:                Tue, 09 Jun 2026   Pseudo R-squ.:                  0.1865
Time:                        11:39:57   Log-Likelihood:                -139.46
converged:                       True   LL-Null:                       -171.44
Covariance Type:            nonrobust   LLR p-value:                 8.447e-14
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -5.0741      0.780     -6.503      0.000      -6.603      -3.545
math           0.0661      0.013      5.154      0.000       0.041       0.091
prog_2         1.1048      0.407      2.711      0.007       0.306       1.903
prog_3         0.3667      0.506      0.724      0.469      -0.626       1.359
==============================================================================

In [26]:
x_train.head()

     math  prog_2  prog_3
152    51       1       0
67     49       1       0
133    57       1       0
59     54       0       0
63     40       0       1

In [27]:
mydata=pd.DataFrame([[70,0,0],[70,1,0],[70,0,1]],columns=x_train.columns)

In [28]:
mydata

   math  prog_2  prog_3
0    70       0       0
1    70       1       0
2    70       0       1

In [29]:
mod2.predict(mydata)

0    0.638170
1    1.926336
2    0.920868
dtype: float64

In [31]:
from statsmodels.discrete.discrete_model import NegativeBinomial as ngb
df = pd.read_excel('CDAC_DataBook (1).xlsx', sheet_name='neg_bin')
prog_dummy = pd.get_dummies(df['prog'], drop_first=True,prefix='prog').astype(int)
df = df.drop('prog', axis=1)
df = pd.concat([df,prog_dummy], axis=1)
x_train, x_test, y_train, y_test = train_test_split(df.drop('daysabs',axis=1), df['daysabs'], test_size=0.2,random_state=20)
x_train1 = sm.add_constant(x_train)
df_train = pd.concat([x_train1,y_train], axis=1)
model3 = ngb.from_formula("daysabs ~ math+prog_General+prog_Vocational", data=df_train).fit()

Optimization terminated successfully.
         Current function value: 2.819371
         Iterations: 19
         Function evaluations: 26
         Gradient evaluations: 26

In [33]:
print(model3.summary())

                     NegativeBinomial Regression Results
==============================================================================
Dep. Variable:                daysabs   No. Observations:                  251
Model:               NegativeBinomial   Df Residuals:                      247
Method:                           MLE   Df Model:                            3
Date:                Tue, 09 Jun 2026   Pseudo R-squ.:                 0.03229
Time:                        11:59:06   Log-Likelihood:                -707.66
converged:                       True   LL-Null:                       -731.28
Covariance Type:            nonrobust   LLR p-value:                 3.104e-10
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept           2.2587      0.144     15.644      0.000       1.976       2.542
math               -0.0070      0.003     -2.506      0.012      -0.012      -0.002
prog_General        0.3942      0.198      1.989      0.047       0.006       0.783
prog_Vocational    -0.7389      0.160     -4.616      0.000      -1.053      -0.425
alpha               0.9326      0.106      8.811      0.000       0.725       1.140
===================================================================================

In [35]:
x_train.head()

     math  prog_General  prog_Vocational
29     79             1                0
90     27             0                0
32     40             0                0
34     68             0                0
182    24             0                1

In [37]:
mydata=pd.DataFrame([[60,0,0],[60,1,0],[60,0,1]],columns=x_train.columns)

In [38]:
model3.predict(mydata)

0    6.285376
1    9.322562
2    3.002024
dtype: float64